apiVersion: v1
kind: Service
metadata:
  name: {{ include "yuval-press.fullname" . }}
  labels:
    {{- include "yuval-press.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      protocol: TCP
      name: http
  selector:
    {{- include "yuval-press.selectorLabels" . | nindent 4 }}
